feature 26 init
NasDiK/PI-S2-OnlineCoursesService pull request #45
Opened 2023-03-30 10:33 UTC by Hardome

2023-04-01 04:44 UTC, NasDiK commented on services/api/controllers/courses.js
> +        .select('group_id');
.pluck('group_id')

2023-04-01 04:45 UTC, NasDiK commented on services/api/controllers/courses.js
> +        .whereIn('groups_users.group_id', groupsIds.map((x) => x.group_id))
и тут мапать не надо будет

2023-04-01 04:45 UTC, NasDiK commented on services/api/controllers/courses.js
> +        .whereIn('groups_users.group_id', groupsIds.map((x) => x.group_id))
Аналогично и тут pluck

2023-04-01 04:45 UTC, NasDiK commented on services/api/controllers/courses.js
> +        .whereIn('id', coursesIds.map((x) => x.course_id))
И тут мапать не надо будет

2023-04-01 04:46 UTC, NasDiK commented on services/api/controllers/courses.js
> +      res.status(400).json({message: exception});
logger.error ещё сделай чтобы в нашу консоль срало)

2023-04-01 04:47 UTC, NasDiK commented on services/api/controllers/courses.js
> +
Лучше убери const controller. А в exports передай объект с двумя функциями {searchCourses,  getCoursesList}

2023-04-01 04:49 UTC, NasDiK commented on services/frontend/src/api/courses.ts
> +  .body({})
А боди нахуя

2023-04-01 04:50 UTC, NasDiK commented on services/frontend/src/components/MainPage/Courses/CoursesPageView.tsx
> +const renderCourse = (course) => (
`const renderCourseCard`

2023-04-01 04:51 UTC, NasDiK requested changes
Давай писать красиво)

2023-04-12 12:22 UTC, Hardome commented on services/api/controllers/groups.js
> +      .select('user_id')
pluck('userId')

2023-04-12 12:23 UTC, Hardome commented on services/api/controllers/groups.js
> +    const userIdsFromDBArray = userIdsFromDB.map((x) => x.user_id);
to delete

2023-04-12 12:25 UTC, Hardome commented on services/api/controllers/groups.js
> +    const objUsers = usersForAdd.map((x) => {
obj || array ???

2023-04-12 12:26 UTC, Hardome commented on services/api/controllers/groups.js
> +    await knex('groups_users')
await Promise.all([
1,
2
])

У тебя две независимые транзакции которые можно выполнить асинхронно друг от друга

2023-04-12 12:27 UTC, Hardome commented on services/api/routers/courses.js
> +coursesRouter.post('/getAllCurses', controller.getAllCurses);
орфографическая ошибка

2023-04-12 12:28 UTC, Hardome commented on services/api/routers/courses.js
> +coursesRouter.post('/getAllCurses', controller.getAllCurses);
+ контроллер переименуй, кринж

2023-04-12 12:28 UTC, Hardome commented on services/api/routers/groups.js
> +/* eslint-disable no-console */
убрать

2023-04-12 12:30 UTC, Hardome commented on services/frontend/src/api/courses.ts
> +const getAllCurses = () => window.api()
Орфографическая ошибка, но уже на фронте

2023-04-12 12:30 UTC, Hardome commented on services/frontend/src/api/courses.ts
> +  .path('/courses/getAllCurses')
\+1

2023-04-12 12:30 UTC, Hardome commented on services/frontend/src/api/courses.ts
> +  getAllCurses,
.

2023-04-12 12:31 UTC, Hardome commented on services/frontend/src/api/groups.ts
> +  createGroup
Что за неопределенность

либо export const

либо const и один экспорт (я к одном экспорту склоняюсь)

2023-04-12 12:35 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/AdminPanelPageView.tsx
> +import DirectoryField from '../../shared/Basic/DirectoryField/DirectoryField';
Напрямую импорт из файла. Там в шаредах лежит index.tsx

Нужно просто сделать `import {Все элементы что тебе надо} from './shared`

Иначе объясни почему напрямую селект не импортишь, ну а чо бы не

2023-04-12 12:36 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/AdminPanelPageView.tsx
> +  let name;
два let вместе в одну строку

2023-04-12 12:36 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/AdminPanelPageView.tsx
> +    getAllCurses().then((x) => {
нейм

2023-04-12 12:36 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/AdminPanelPageView.tsx
> +import {getAllCurses} from '../../../api/courses';
нейм

2023-04-12 12:37 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/AdminPanelPageView.tsx
> +        subGroup: subGroups});
к единообразию нейминга переменных (subgroup)

2023-04-12 12:37 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/AdminPanelPageView.tsx
> +      const subGroups = groups.map((el) => {
es-lint use destructuring

2023-04-12 12:38 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/AdminPanelPageView.tsx
> +  const options = mainElement?.courses.map((el) => {
[дестрк](https://learn.javascript.ru/destructuring)

2023-04-12 12:39 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/AdminPanelPageView.tsx
> +              type={2}
enum

2023-04-12 12:40 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/AdminPanelPageView.tsx
> +          onClose={ModalSetClose}
Название функций с маленькой

2023-04-12 12:41 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/AdminPanelPageView.tsx
> +        onClick={modalOpen}
openModal

Объект+действие - это состояние сущности

а наоборот - это действие

2023-04-12 12:42 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/AdminPanelPageView.tsx
> +          buttonText={'Добавить группу'}
зачем buttonText

2023-04-12 12:42 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/AdminPanelPageView.tsx
> +          options={options}
options тоже не надо - модал всего лишь обертка

2023-04-12 12:45 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/components/AddUserSelectComponent.tsx
> +import DirectoryField from '../../../shared/Basic/DirectoryField/DirectoryField';
импорты из общей

2023-04-12 12:46 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/components/AddUserSelectComponent.tsx
> +import Typography from '../../../shared/Basic/Typography/Typography';
.

2023-04-12 12:46 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/components/AddUserSelectComponent.tsx
> +import {fieldType} from '@local/enums/dist/shared';
Неправильные импорт. Должен быть @local/enums/shared

2023-04-12 12:47 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/components/AddUserSelectComponent.tsx
> +  const [usersIds, setusersIds]: any = useState<any>([]);
КамелКейс функция присвоения

2023-04-12 12:47 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/components/AddUserSelectComponent.tsx
> +    getUsersByRole(12).then((x) => {
Что за мэджик намбер). Хуйня переделывай

2023-04-12 12:48 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/components/AddUserSelectComponent.tsx
> +    getUsersByRole(12).then((x) => {
бай рол нейм

2023-04-12 12:49 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/components/AddUserSelectComponent.tsx
> +  const optionsUsers = users?.users.map((el) => {
Почему объект и его свойства называются одинаково?

Или всё таки не объектъ

2023-04-12 12:49 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/components/AddUserSelectComponent.tsx
> +  const optionsUsers = users?.users.map((el) => {
+ use destructuring

2023-04-12 12:50 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/components/AddUserSelectComponent.tsx
> +  const saveChanges = () => {
() => `method()`

А в чем смысл этого метода

2023-04-12 12:51 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/components/AddUserSelectComponent.tsx
> +        onChange={(val) => setusersIds(val)}
нейм

2023-04-12 12:52 UTC, Hardome commented on services/frontend/src/components/MainPage/AdminPanel/components/AddUserSelectComponent.tsx
> +        variant={'multi'}
isMulti пропса договоривались же)

2023-04-12 12:53 UTC, Hardome commented on services/frontend/src/components/MainPage/Courses/Components/Card.module.scss
> +
убирай энтер

2023-04-12 12:53 UTC, Hardome commented on services/frontend/src/components/MainPage/Courses/Components/CourseCard.tsx
> +import Typography from '../../../shared/Basic/Typography/Typography';
импорты шаредов правь

2023-04-12 12:53 UTC, Hardome commented on services/frontend/src/components/MainPage/Courses/Components/CourseCard.tsx
> +  const moveToCourse = () => {
бесполезный метод

2023-04-12 12:54 UTC, Hardome commented on services/frontend/src/components/MainPage/Courses/Components/CourseCard.tsx
> +        <div className={s.courseHeader}>
.header

2023-04-12 12:54 UTC, Hardome commented on services/frontend/src/components/MainPage/Courses/Components/CourseCard.tsx
> +          <div className={s.courseDescription}>
.description

2023-04-12 12:55 UTC, Hardome commented on services/frontend/src/components/MainPage/Courses/Components/CourseCard.tsx
> +  id: PropTypes.node,
Даже не хочу  это комментировать. Читай доку npm https://www.npmjs.com/package/prop-types

2023-04-12 12:56 UTC, Hardome commented on services/frontend/src/components/shared/Basic/DirectoryField/DirectoryField.tsx
> +import {SelectChangeEvent} from '@mui/material/Select';
удалить неиспользуемое

2023-04-12 12:57 UTC, Hardome commented on services/frontend/src/components/shared/Basic/DirectoryField/DirectoryField.tsx
> +  variant?: 'outline' | 'standart' | 'multi',
isMulti: boolean пропса

2023-04-12 12:58 UTC, Hardome commented on services/frontend/src/components/shared/Basic/DirectoryField/FieldTypes/Select.tsx
> +    case 'multi':
мульти убрать

2023-04-12 12:59 UTC, Hardome commented on services/frontend/src/components/shared/Basic/Modal/Modal.tsx
> +  variant?: 'basic' | 'primary' | 'roundThin' | 'icon',
Зачем так много вариантов модала если  используется только 1

2023-04-12 12:59 UTC, Hardome commented on services/frontend/src/components/shared/Basic/Modal/Modal.tsx
> +  buttonText?: string,
Сошлись на удалении этой пропсы

2023-04-12 13:00 UTC, Hardome commented on services/frontend/src/components/shared/Basic/Modal/Modal.tsx
> +  onClick?: any, //функция обработчика
У меня есть пример использования фунцкий в интерфейсы

2023-04-12 13:00 UTC, Hardome commented on services/frontend/src/components/shared/Basic/Modal/Modal.tsx
> +  variant?: 'basic' | 'primary' | 'roundThin' | 'icon',
\+ удалить неиспользуемые пропсы

2023-04-12 13:04 UTC, Hardome commented on services/frontend/src/components/shared/Basic/Modal/ModalTypes/style.modules.scss
> +style{
delete to ili eto

2023-04-12 13:05 UTC, Hardome commented on services/frontend/src/components/shared/Basic/Typography/Typography.tsx
> +    body18: {
так 18 или 16

2023-04-13 07:18 UTC, NasDiK commented on services/api/routers/courses.js
> +/* eslint-disable no-console */
лишнее дерьмо (некритично)

2023-04-13 07:18 UTC, NasDiK commented on services/api/routers/groups.js
> +const controller = require('../controllers/groups');
groupsController (некритично)

2023-04-13 07:19 UTC, NasDiK commented on services/api/services/courses/getCoursesListByUsers.js
> +    return await knex('courses')
я запрещаю вам писать return await!

Critical!

2023-04-13 07:20 UTC, NasDiK commented on services/api/services/courses/getCoursesListByUsers.js
> +    return exception;
???? А в чем смысл try{} catch{} тогда если return exception

2023-04-13 07:32 UTC, NasDiK requested changes

2023-04-13 07:32 UTC, NasDiK commented on services/api/services/groups/getGroups.js
> +    return await knex('groups').select('id', 'title', 'course_id');
return await

2023-04-13 07:32 UTC, NasDiK commented on services/api/services/groups/getUsersInGroup.js
> +    return await knex('groups_users')
return await

2023-04-13 07:32 UTC, NasDiK commented on services/api/services/groups/saveGroupChanges.js
> +    const users = usersForAdd.map((x) => {
Раз уже править будешь напиши map((userId))

чтобы никаких magic x в формулах

2023-04-13 07:32 UTC, NasDiK commented on services/api/services/groups/saveGroupChanges.js
> +        .where('group_id', groupId)
await не нужен. Promise.all запускает две операции одновременно

А await Promise.all() дожидается пока все промисы завершатся успешно https://learn.javascript.ru/promise-api

2023-04-13 07:32 UTC, NasDiK commented on services/api/services/courses/getAllCourses.js
> +    return await knex('courses').select('id', 'title', 'description');
return await

2023-04-13 07:32 UTC, NasDiK commented on services/frontend/src/components/MainPage/Courses/CoursesPageView.tsx
> +const renderCourseCard = (course) => (
Тут бы деструктор (не критично)

2023-04-13 07:32 UTC, NasDiK commented on services/frontend/src/components/shared/Basic/DirectoryField/DirectoryField.tsx
> +  'value'?: string | number | number[],
Тут передаётся string | number

Предполагаю что ты делал для передачи с пропсой isMulti

А что делать если я хочу multi по строкам?))

Подсказка, добавь поддержку множества строк в value

2023-04-13 07:32 UTC, NasDiK commented on services/frontend/src/components/shared/Basic/DirectoryField/FieldTypes/Select.tsx
> +  variant?: 'outline' | 'normal' | 'multi',
Если есть вариант multi зачем isMulti и наоборот

Я верно понимаю, что если я выбрал variant={'мульти'} у меня может быть одиночный селект

2023-04-13 07:32 UTC, NasDiK commented on services/frontend/src/components/shared/Basic/DirectoryField/FieldTypes/Select.tsx
> +  multiple?: boolean,
В добавок к верхнему. Чтобы включить мульти мне нужно все три пропсы ебнуть? multiple, isMulti, variant = 'multi' ???

А может лучше одну?) 

critical!!!!

2023-04-13 07:32 UTC, NasDiK commented on services/frontend/src/components/shared/Basic/Modal/ModalTypes/BasicModal.tsx
> +        <div className={s.style}>
Если здесь есть s.style

То зачем (смотри выше)

2023-04-13 07:32 UTC, NasDiK commented on services/frontend/src/components/shared/Basic/Modal/ModalTypes/BasicModal.tsx
> +const style = {
Смотри ниже

2023-04-13 07:32 UTC, NasDiK commented on services/frontend/src/components/shared/Basic/Modal/ModalTypes/style.modules.scss
> +style{
Не исправлено

2023-04-13 07:41 UTC, Hardome commented on services/api/services/groups/saveGroupChanges.js
> +        .where('group_id', groupId)
ссылку вставил - день прошёл успешно

2023-04-15 16:22 UTC, NasDiK approved these changes
3 косяка, но писать я о них конечно же не буду

2023-04-16 15:27 UTC, merged