feature 46 init (не смотри)
NasDiK/PI-S2-OnlineCoursesService pull request #50
Opened 2023-04-22 20:46 UTC by Hardome

2023-04-27 15:49 UTC, NasDiK requested changes
Решение построенное на костылях. Проект большой, понимаю. Но на шп такой делать нельзя. Бери проект мелкий, но меткий

2023-04-27 15:49 UTC, NasDiK commented on services/api/services/groups/getGroupsById.js
> +    if (groupId === undefined) {
!groupId звучит лучше

[Recommend]

2023-04-27 15:49 UTC, NasDiK commented on services/api/services/tasks/getAnswersLogs.js
> +    const answers = knex('tasks_logger')
Бля кринж, почему бы не сделать await knex и вернуть answers, На работебы за такое выдрали

[Recommend]

2023-04-27 15:49 UTC, NasDiK commented on services/api/services/tasks/getAnswersLogs.js
> +const {tasks: {action}} = require('@local/enums');
Можно было написать `const {action} = require('@local/enums/tasks')`

[Recommend]

2023-04-27 15:49 UTC, NasDiK commented on services/frontend/src/components/MainPage/Students/components/ExportCSV.tsx
> +  const tasks = useSelector((stores: any) => stores.studentsStore.tasks);
Тут можно было написать
`const tasks = useSelector(({studentsStore}) => studentsStore.tasks)`

[Recommend]

2023-04-27 15:49 UTC, NasDiK commented on services/frontend/src/components/MainPage/Students/components/ExportCSV.tsx
> +  const users = useSelector((stores: any) => stores.studentsStore.users);
Слишком жирная компонента. И непонятно зачем все эти вычисления. Попробуй сделать функцию, которая все тоже самое делает, но только когда я этого захочу/нажму на кнопку, а не когда кнопка просто нарисовалась

[TO FIX]

2023-04-27 15:49 UTC, NasDiK commented on services/frontend/src/components/MainPage/Students/components/ExportCSV.tsx
> +  if (tasks !== undefined) {
!tasks

2023-04-27 15:49 UTC, NasDiK commented on services/frontend/src/components/MainPage/Students/components/ExportCSV.tsx
> +  if (users !== undefined && tasks !== undefined) {
!users && !tasks

2023-04-27 15:49 UTC, NasDiK commented on services/frontend/src/components/MainPage/Students/components/ExportCSV.tsx
> +        if (answers !== undefined) {
!answers

2023-04-27 15:49 UTC, NasDiK commented on services/frontend/src/components/MainPage/Students/components/ExportCSV.tsx
> +              if (answer.value === 'false') {
value === 'false?
Что за подкос строки под булеан тип. На работе бы отодрали. В рамках учебног опроекта который все мои силы высосал - норм.

[Recommend to FIX, non critical]

2023-04-27 15:49 UTC, NasDiK commented on services/frontend/src/components/MainPage/Students/components/ExportCSV.tsx
> +              } else if (answer.note !== null) {
!answer.note

2023-04-27 15:49 UTC, NasDiK commented on services/frontend/src/components/MainPage/Students/components/ExportCSV.tsx
> +            if (task.id === 999) {
Что за магическое число? Это для себя, в душе не чаю что тут происходит)

2023-04-27 15:49 UTC, NasDiK commented on services/frontend/src/components/MainPage/Students/components/ExportCSV.tsx
> +  const exportToCSV = (dataToExport, fileNameToExport) => {
Вот все что выше в подобную структуру оформи пожалуйста, а то фронт не резиновый, нельзя так нагружать. Да и впринципе представь сколько вычисление незачем делается

2023-04-27 15:49 UTC, NasDiK commented on services/frontend/src/components/MainPage/Students/components/StudentsTable.tsx
> +import TableBody from '@mui/material/TableBody';
Что то мне подсказывает что можно написать общий импорт 
`import {Table, TableBody, ...} from '@mui/material`

[Recommend TO FIX]

2023-04-27 15:49 UTC, NasDiK commented on services/frontend/src/components/MainPage/Students/components/StudentsTable.tsx
> +  const tasksComponent = [
Это что ещё за key {'start'} ты вообще знаешь за что этот key отвечает??

2023-04-27 15:49 UTC, NasDiK commented on services/frontend/src/components/MainPage/Students/components/StudentsTable.tsx
> +  if (tasks !== undefined && tasks.length > 1) {
Вынести во внешнюю функцию (на подобии моих группировок для селектора в других модуляъ системы). Почему у тебя компонента дохера умные. Они должно только лишь отображать данные из сторы (в идеале), а они у тебя суперпуперумняжки которые и обрабатывают данные и читают и отправляют, нельзя так

[TO FIX]

Ожидаемый результат: Со сторы тебе приходит уже готовый компонент (со сдано, 0 и оценкой), а здесь ты по красоте отображашь то что хранится в сторе. Установка значения в стору можно сделать из внешних функций, вызывать их можно и тут

2023-04-27 15:49 UTC, NasDiK commented on services/frontend/src/components/MainPage/Students/components/StudentsTableComponent.tsx
> +    if (groupId !== undefined) {
всё также undefined на !

2023-04-27 15:49 UTC, NasDiK commented on services/frontend/src/stores/components/Students/StudentsReducer.ts
> +const reducer = createReducer(initialState, {
Логику группировки кстати можно сюда вынести, как у меня в feature/47. Это значительно удобнее поддерживать и компонента упрощается в сотни тысяч раз

2023-04-27 17:21 UTC, Hardome commented on services/frontend/src/components/MainPage/Students/components/StudentsTable.tsx
> +  const tasksComponent = [
знаю, там похуй было на эти элементы

2023-04-28 02:29 UTC, NasDiK approved these changes
Копмпоненты стали чище, красивее и читабельнее, семён красавчик

2023-04-30 16:18 UTC, merged