add authPage
NasDiK/PI-S2-OnlineCoursesService pull request #9
Opened 2023-02-27 11:59 UTC by Hardome

2023-02-27 12:13 UTC, NasDiK requested changes

2023-02-27 12:13 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.scss
> +.password-group{
Это чё бля)

2023-02-27 12:13 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.scss
> +  position: absolute;
.

2023-02-27 12:13 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.scss
> +  right: 66.58%;
.

2023-02-27 12:13 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.scss
> +  top: 0;
чё за абсолюты) давай на флексах. Читер на фигме

2023-02-27 12:13 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.scss
> +  top: 0;
Адаптив запусти, посмотри своё детище

2023-02-27 12:13 UTC, NasDiK commented on services/frontend/src/components/shared/Basic/Button/ButtonTypes/PrimaryButton.tsx
> +    widthFull: {
fullWidth + в type главного Button не отражено

2023-02-27 12:13 UTC, NasDiK commented on services/frontend/src/components/shared/Basic/Button/ButtonTypes/PrimaryButton.tsx
> +  const {children, size = 'small', width = 'widthFull'} = props;
.

2023-02-27 12:13 UTC, NasDiK commented on services/frontend/src/components/shared/Basic/Button/ButtonTypes/PrimaryButton.tsx
> +          [classes.widthFull]: width === 'widthFull'
Переназвать класс, в остальном суть уловил)

2023-02-27 12:13 UTC, NasDiK commented on services/frontend/src/components/shared/Basic/DirectoryField/FieldTypes/TextField.tsx
> +  width?: 'full'
А почему вариация из стрингов? Либо fullWidth либо нет

P.s. намёк на boolean

2023-02-27 12:13 UTC, NasDiK commented on services/frontend/src/components/shared/Basic/DirectoryField/FieldTypes/TextField.tsx
> +  width?: 'full'
Переделать на fullWidth

2023-02-27 12:13 UTC, NasDiK commented on services/frontend/src/pages/AuthPage.tsx
> +    <div className={'auth-form'}>
scss позволяет вкладывать элемент в элемент

Подумай как можно избавиться от длинных названий

Пример

```
.form {
 .login{
 }
}

<div class={s.form}>
<div class={s.login}></div>
</div>
```

2023-02-27 12:13 UTC, NasDiK commented on services/frontend/src/components/shared/Basic/Button/ButtonTypes/PrimaryButton.tsx
> +          [classes.widthFull]: width === 'widthFull'
Переделать на булеан -> оператор !!fullWidth

2023-02-27 17:14 UTC, NasDiK requested changes

2023-02-27 17:14 UTC, NasDiK commented on services/frontend/src/pages/AuthPage.tsx
> +      <div className={'form-top'}>
Зачем ты называешь их form-top form-top-text

Я же попросил избавиться от длинных названий

2023-02-27 17:14 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.scss
> +  position: absolute;
абсолют

2023-02-27 17:14 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.scss
> +.form-top{
что за форм топ и абсолют

2023-02-27 17:32 UTC, NasDiK requested changes

2023-02-27 17:32 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.scss
> +  position: fixed;
А нафига фиксед?) 
https://learn.javascript.ru/css-units#otnositelno-ekrana-vw-vh-vmin-vmax

2023-02-27 17:37 UTC, NasDiK commented on services/frontend/src/pages/AuthPage.tsx
> +import '../components/AuthPage/AuthPageView.scss';
А, нихуя себе. Сразу не заметил. А нахуй ты импортишь в общий?)

Назови файл *.module.scss

И импортируй как объект с неймами 
`import s from '*/module.scss'`

Но это не вся беда. 
Мы с тобой говорили что здесь будет собачка редакса. Папка pages будет отвечать за первичную отрисовку компоненты. И она будет оборачиваться в redux Provider

Создай компоненту AuthPageView в components/AuthPage и туда перенеси весь код

**Глобально класснеймы выдавать запрещено! Они встраиваются в общую таблицу стилей. Может потом конфликт всплыть**

Импорт через модули добавляет неповторяющийся шифр в класснейм и тем является безопасным

2023-02-27 17:38 UTC, NasDiK requested changes
to fix

2023-02-27 17:39 UTC, NasDiK commented on services/frontend/src/pages/AuthPage.tsx
> +  <div className='auth-page'>
Все строки оборачиваем в {}

2023-02-27 18:22 UTC, Hardome commented
ПАПА НЕ РУГАЙ!

2023-02-27 18:32 UTC, NasDiK requested changes

2023-02-27 18:32 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.module.scss
> +      gap: 8px;
Переделать на margin

2023-02-27 18:32 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.module.scss
> +      color: #FFFFFF;
Тут допустимо. В будущем учти, что будет использовать файлик variables.scss в корне проекта)

2023-02-27 18:32 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.module.scss
> +      top: 5px;
margin-top: 5px;

2023-02-27 18:32 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.module.scss
> +      height: 20px;
У кнопки height убери. Он будет зависеть от typography

Хардкодить высоту и ширину надо осторожно же)

Тут допустимо только на общий контейнер, и логотип

2023-02-27 18:32 UTC, NasDiK commented on services/frontend/src/components/shared/Basic/Button/ButtonTypes/PrimaryButton.tsx
> +  const {children, size = 'small', width = true} = props;
Пропса fullWidth, а деструктуризируешь width? И как?)

2023-02-27 18:32 UTC, NasDiK commented on services/frontend/src/components/shared/Basic/Button/ButtonTypes/PrimaryButton.tsx
> +          [classes.fullWidth]: width
.

2023-02-27 18:32 UTC, NasDiK commented on services/frontend/src/components/shared/Basic/DirectoryField/FieldTypes/TextField.tsx
> +      width: '100%'
\+ position: relative;

2023-02-27 18:32 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.tsx
> +          <Button variant={'primary'}>{'Войти'}</Button>
Пропсу fullWidth добавил? Используй!) ахах

2023-02-27 18:35 UTC, NasDiK commented on services/frontend/src/components/shared/Basic/Button/ButtonTypes/PrimaryButton.tsx
> +  const {children, size = 'small', width = true} = props;
И значение по умолчанию true убирай. У меня все кнопки теперь в проекте будут вытягиваться как баян

2023-02-27 18:55 UTC, NasDiK requested changes

2023-02-27 18:55 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.module.scss
> +      height: 51px;
размер шапки не должен быть фиксой. Фиксой может быть весь контейнер, но верхнюю полосочку в этом случае не надо хардкодить

51 пиксель кстати это баг фигмы - бордюр внешний 1 пиксель всегда пририсовывает, прими это как факт к сожалению)

2023-02-27 18:55 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.module.scss
> +    background: #FFFFFF;
white?

2023-02-27 18:55 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.module.scss
> +      background: #000000;
Black?

2023-02-27 18:55 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.module.scss
> +    border: 1px solid #000000;
black?

2023-02-27 18:55 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.module.scss
> +        width: 335px;
А пропса зачем тогда? или что это за филд

2023-02-27 18:55 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.module.scss
> +      color: #FFFFFF;
white?

2023-02-27 18:55 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.module.scss
> +      width: 64px;
Ровно такой же вопрос. Прокидывал пропсу на полную ширину и захардкодил ширину. Кто тут лишний? пропса или width свойство

2023-02-27 18:55 UTC, NasDiK commented on services/frontend/src/components/AuthPage/AuthPageView.module.scss
> +      width: 64px;
Если отступ нужен используй margin. А вообще если button по размеру не соответствует макету забей, главное чтобы шрифт внутри соответствовал. Я потом synch задачу делать буду, и меняя шареду сразу весь проект починю

2023-02-27 19:15 UTC, NasDiK approved these changes

2023-02-27 19:24 UTC, NasDiK approved these changes

2023-02-28 18:42 UTC, NasDiK commented
1) Факт:
![image](https://user-images.githubusercontent.com/98635531/221948100-00bc1834-6948-4fa5-9391-39378dbbb299.png)
Макет (12 px):
![image](https://user-images.githubusercontent.com/98635531/221948297-5b432cd3-dfb1-41ba-b435-7cf404699824.png)

2023-02-28 18:43 UTC, merged